# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# PodDisruptionBudget See
# https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
#
# This PDB forces a minumum of two elasticsearch data nodes are available.
#
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-data
spec:
  minAvailable: 2
  selector:
    matchLabels:
      component: elasticsearch
      role: data
